### PR TITLE
Add Debian 10 and Red Hat 8 to the supported OS list

### PR DESCRIPTION
**Pull request by ekohl**
This also adds CentOS since it's equivalent to Red Hat.

I'm not sure about the regular procedure to add distro support. I don't see any acceptance tests and don't have the capacity to properly test this myself.

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
It works, I'm already using it on EL8.

Might as well add OEL 8 to the mix as well.

**Comment by ekohl** [comment]
Looks like the CI infra needs to be updated from Precise to Xenial

**Comment by raphink** [comment]
@ekohl I've switched the travis distro in #22, can you rebase?

**Comment by ekohl** [comment]
Rebased

**Comment by ekohl** [comment]
This is now green. Anything holding a merge back?

**Comment by trevor-vaughan** [comment]
@raphink I would like this as well. Also, any time frame for a new release once this is in? It looks like there were some minor bugs that were fixed that it would be nice to have.

**Pull request merged**
